"""
Public Health Signal Fusion Agent - Config Package
"""

from config.settings import (
    APP_NAME,
    APP_VERSION,
    DEFAULT_POLLING_INTERVAL_SECONDS,
    AUTONOMOUS_LOOP_ENABLED_DEFAULT,
    DEMO_DISTRICTS,
    DEFAULT_DISTRICT_METADATA,
    SIGNAL_WEIGHTS,
    MAX_AGREEMENT_BONUS,
    ALERT_RISK_THRESHOLD,
    ALERT_CONFIDENCE_THRESHOLD,
    GEMINI_SYSTEM_PROMPT,
)

__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "DEFAULT_POLLING_INTERVAL_SECONDS",
    "AUTONOMOUS_LOOP_ENABLED_DEFAULT",
    "DEMO_DISTRICTS",
    "DEFAULT_DISTRICT_METADATA",
    "SIGNAL_WEIGHTS",
    "MAX_AGREEMENT_BONUS",
    "ALERT_RISK_THRESHOLD",
    "ALERT_CONFIDENCE_THRESHOLD",
    "GEMINI_SYSTEM_PROMPT",
]
