"""
Public Health Signal Fusion Agent - Gemini Contract Models
Strict input payload and strict JSON output schema models for Gemini 2.5 Flash.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class GeminiReasoningInput:
    """Read-only data package provided to Gemini Reasoning Agent."""
    cycle_id: str
    timestamp: str
    affected_district: str
    overall_risk_score: float
    confidence_score: float
    risk_level: str
    district_ranking: List[Dict[str, Any]]  # List of dicts with district name, risk, rank
    signal_breakdown: Dict[str, Dict[str, Any]]  # Per-source score + status
    raw_evidence_summary: List[str]  # Bullet points of key raw observations


# --- Strict Section 6 Gemini JSON Contract Output Schema ---
GEMINI_OUTPUT_JSON_SCHEMA: Dict[str, Any] = {
    "type": "OBJECT",
    "properties": {
        "risk_level": {
            "type": "STRING",
            "description": "Risk level corresponding to Python score: LOW, MODERATE, HIGH, or CRITICAL"
        },
        "confidence": {
            "type": "NUMBER",
            "description": "Confidence score calculated by Python engine (0.0 to 100.0)"
        },
        "affected_district": {
            "type": "STRING",
            "description": "Primary district evaluated"
        },
        "reasoning_trace": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "description": "Step-by-step epidemiological reasoning trace explaining why scores reached this level (max 4 bullets)"
        },
        "recommendations": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "description": "Actionable public health recommendations referencing weather, disease, hospital load, AQI, population, and resource availability"
        },
        "incident_summary": {
            "type": "STRING",
            "description": "Formal drafted incident summary narrative for health officials"
        },
        "public_advisory": {
            "type": "STRING",
            "description": "A high-impact 2-sentence public health advisory statement for citizens of the affected district."
        },
        "dos_and_donts": {
            "type": "OBJECT",
            "properties": {
                "dos": {
                    "type": "ARRAY",
                    "items": {"type": "STRING"},
                    "description": "Exactly 3 actionable, positive recommendations (Do's) for the general public."
                },
                "donts": {
                    "type": "ARRAY",
                    "items": {"type": "STRING"},
                    "description": "Exactly 3 specific hazardous actions or behaviors to avoid (Don'ts)."
                }
            },
            "required": ["dos", "donts"],
            "description": "Public-facing Do's and Don'ts behavioral directives."
        },
        "whatsapp_message": {
            "type": "STRING",
            "description": "A ready-to-dispatch broadcast-style WhatsApp message containing structured bullet points, clear headings, warning emojis, and a citizen help line."
        }
    },
    "required": [
        "risk_level",
        "confidence",
        "affected_district",
        "reasoning_trace",
        "recommendations",
        "incident_summary",
        "public_advisory",
        "dos_and_donts",
        "whatsapp_message"
    ]
}


@dataclass
class GeminiReasoningOutput:
    """Parsed response object matching PRD Section 6 JSON contract."""
    risk_level: str
    confidence: float
    affected_district: str
    reasoning_trace: List[str]
    recommendations: List[str]
    incident_summary: str
    public_advisory: str = ""
    dos_and_donts: Dict[str, List[str]] = field(default_factory=dict)
    whatsapp_message: str = ""
    incident_report: str = ""
    resource_summary: str = ""
    is_fallback: bool = False  # Set to True if generated by local fallback engine when Gemini fails
